services:
  wg-easy:
    network_mode: "host"
    environment:
      - WG_HOST=92.113.34.197
      - PASSWORD_HASH=$$2b$$12$$oEsWNfwzdmpjrwQC0KXpVuv3MCrEZpxuW4Dzmmg8ZzpGjRKXkqbfq
      - PORT=51821
      - WG_PORT=51820
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    restart: unless-stopped
    volumes:
      - ./.wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
